AllCops:
  Exclude:
    - 'inspector-status/**/*'
    - 'features/**/*'
    - 'pipeline/lib/cfn_nag/**/*'
    - 'pipeline/tasks/security-test.rake'

# CloudFormation DSL
BlockLength:
  Max: 500

ClassLength:
  Max: 150

MethodLength:
  Max: 30

AbcSize:
  Enabled: false

NumericLiteralPrefix:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Description: 'Use snake_case for source file names.'
  StyleGuide: '#snake-case-files'
  Enabled: false
