AllCops:
  Exclude:
    - 'inspector-status/**/*'
    - 'features/**/*'
    - 'pipeline/lib/cfn_nag/**/*'

# CloudFormation DSL
BlockLength:
  Max: 500

ClassLength:
  Max: 150

MethodLength:
  Max: 30

AbcSize:
  Enabled: false

NumericLiteralPrefix:
  Enabled: false

Metrics/LineLength:
  Max: 120
